// <auto-generated />
using JunBatchCodeFirstApproachImpl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JunBatchCodeFirstApproachImpl.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Dept", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Did"));

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Did");

                    b.ToTable("depts");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Emp", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<int>("Did")
                        .HasColumnType("int");

                    b.Property<int>("Mid")
                        .HasColumnType("int");

                    b.Property<int>("Rid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("esalary")
                        .HasColumnType("float");

                    b.HasKey("eid");

                    b.HasIndex("Did");

                    b.HasIndex("Mid");

                    b.HasIndex("Rid");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Employee", b =>
                {
                    b.Property<int>("eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eid"));

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("esalary")
                        .HasColumnType("float");

                    b.HasKey("eid");

                    b.HasIndex("ManagerId");

                    b.ToTable("emps");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Manager", b =>
                {
                    b.Property<int>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mid"));

                    b.Property<string>("Mname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mid");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Managers", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.ToTable("managers");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Role", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rid"));

                    b.Property<string>("Rname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rid");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Student", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<double>("Fees")
                        .HasColumnType("float");

                    b.Property<string>("Scourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sphoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sid");

                    b.ToTable("students");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Emp", b =>
                {
                    b.HasOne("JunBatchCodeFirstApproachImpl.Models.Dept", "dept")
                        .WithMany("emps")
                        .HasForeignKey("Did")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JunBatchCodeFirstApproachImpl.Models.Manager", "manager")
                        .WithMany("emps")
                        .HasForeignKey("Mid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JunBatchCodeFirstApproachImpl.Models.Role", "role")
                        .WithMany("emps")
                        .HasForeignKey("Rid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("dept");

                    b.Navigation("manager");

                    b.Navigation("role");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Employee", b =>
                {
                    b.HasOne("JunBatchCodeFirstApproachImpl.Models.Managers", "mans")
                        .WithMany("employees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("mans");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Dept", b =>
                {
                    b.Navigation("emps");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Manager", b =>
                {
                    b.Navigation("emps");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Managers", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("JunBatchCodeFirstApproachImpl.Models.Role", b =>
                {
                    b.Navigation("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
